import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
});
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="ca" className={`${montserrat.variable}`}>
        <body className="font-sans"> {/* Això usarà la --font-sans que hem definit al CSS */}
          {children}
        </body>
      </html>
  );
}
